name: CI

on:
  workflow_dispatch:
    branches:
     - "main"
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  schedule:
    # Weekly tests run on main by default:
    #   Scheduled workflows run on the latest commit on the default or base branch.
    #   (from https://help.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events-schedule)
    - cron: "0 0 * * 0"

jobs:
  test:
    name: Test on ${{ matrix.os }}, Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Additional info about the build
        shell: bash
        run: |
          uname -a
          df -h
          ulimit -a

      # More info on options: https://github.com/marketplace/actions/provision-with-micromamba
      - uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: requirements.yaml
          environment-name: generate_alchemical_lammps_inputs
          init-shell: bash
          cache-environment: true
          post-cleanup: 'all'

          condarc: |
            channels:
              - conda-forge
              - defaults

          create-args: >-
            python=${{ matrix.python-version }}
            pytest
            pytest-cov
            codecov

      - name: Install package
        # conda setup requires this special shell
        shell: bash -l {0}
        run: |
          python -m pip install . --no-deps
          micromamba list

      - name: Run tests
        # conda setup requires this special shell
        shell: bash -l {0}
        run: |
          pytest -v --cov=generate_alchemical_lammps_inputs --cov-report=xml --color=yes src/tests/

      - name: CodeCov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
          flags: unittests
          name: codecov-${{ matrix.os }}-py${{ matrix.python-version }}

  docs:
    name: Build docs on ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: usnistgov/Docs4NIST@0.7.2
        with:
          docs-folder: docs/
          conda-environment: docs/requirements.yaml
          formats: |-
            epub
            html
